name: Build

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare artifact values
        run: |
          ARTIFACTS_SHA=$(git rev-parse HEAD)
          echo "Artifact SHA: $ARTIFACTS_SHA"
          BUILD_ARTIFACTS=BuildArtifacts_${ARTIFACTS_SHA}
          echo "ARTIFACTS_SHA=$ARTIFACTS_SHA" >> $GITHUB_ENV

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: Artifacts_${{ env.ARTIFACTS_SHA }}
          path: 
            ./*.txt
          retention-days: 3


  can_use_artifact:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4 # Needed to get the sha??

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.1

      - name: List files in Repository including Artifact(s)
        run: |
          ARTIFACTS_SHA=$(git rev-parse HEAD)
          echo "Files:"
          ls -R
          echo "Expected artifacts folder is: Artifacts_$ARTIFACTS_SHA - files:"
          ls Artifacts_${ARTIFACTS_SHA}
          echo "Renaming artifacts folder to static name:"
          mv Artifacts_${ARTIFACTS_SHA} artifacts
          ls
