name: Post Build
on: 
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  test_get_artifact:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: What do we have of environments?
      run: |
        ls -R
        ARTIFACTS_SHA=$(git rev-parse HEAD)
        echo "Expected artifacts folder is: Artifacts_$ARTIFACTS_SHA"
        echo "ARTIFACTS_SHA=$ARTIFACTS_SHA" >> $GITHUB_ENV
    - name: Download the Build Artifact
      uses: actions/download-artifact@v4.1.1
      with:
#        name: Artifacts_${{ env.ARTIFACTS_SHA }}
        name: Artifacts_7a0f9ff24783dcca963ad3d483d62d52191281bd
        path: ./arts
        github-token: ${{ secrets.GITHUB_TOKEN }} # ${{ secrets.GH_PAT }}  # optional
        run-id: 7725542784 # 7725542784/artifacts/1208574191
        

    - name: Repository after download
      run: |
        ls -R
        
