name: Post Build
on: 
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: What do we have of environments?
      run: |
        ls -R
        ARTIFACTS_SHA=$(git rev-parse HEAD)
        echo "Expected artifacts folder is: Artifacts_$ARTIFACTS_SHA"
        echo "ARTIFACTS_SHA=$ARTIFACTS_SHA" >> $GITHUB_ENV
    - name: Download the Build Artifact
      uses: actions/download-artifact@v4.1.1
      with:
        name: Artifacts_${{ env.ARTIFACTS_SHA }}
#        github-token: ${{ secrets.GH_PAT }}  # optional
#        run-id: ??
        
