name: Post Build
on: 
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      RUN_ID:
        type: text
        required: true
        description: Type in the Run ID from the Build step containing the artifact.
  
jobs:
  test_get_artifact:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Expect not to check out any files - but need the SHA info for later use
      with:
        sparse-checkout: |
          nothing
        sparse-checkout-cone-mode: false  
    - name: Set up download environment
      run: |
        ls -R

        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]
        then
           echo "Getting run id from workflow_dispatch - input: ${{ inputs.RUN_ID }}"
           echo "BUILD_RUN_ID=${{ inputs.RUN_ID }}" >> $GITHUB_ENV
        else
           echo "Getting run id from workflow_run: ${{ github.event.workflow_run.id }}"
           echo "BUILD_RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV
        fi

        echo "Is it already here? ... $BUILD_RUN_ID / ${{ env.BUILD_RUN_ID }} ...
        ARTIFACTS_SHA=$(git rev-parse HEAD)
        echo "Expected artifacts folder is: Artifacts_$ARTIFACTS_SHA"
        echo "ARTIFACTS_SHA=$ARTIFACTS_SHA" >> $GITHUB_ENV
#        echo "Artifact was made from run ID: ${{github.event.workflow_run.id }}"
#        echo "ARTIFACT_RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV
    - name: Download the Build Artifact
      uses: actions/download-artifact@v4.1.1
      with:
#        name: Artifacts_${{ env.ARTIFACTS_SHA }} # If specified, files will be extracted to the root folder!
        github-token: ${{ secrets.GITHUB_TOKEN }} # ${{ secrets.GH_PAT }}  # optional
# Was:        run-id: ${{ github.event.workflow_run.id }}
        run-id: ${{ env.BUILD_RUN_ID }}

    - name: Repository after download
      run: |
        ls -R
# Optionally - rename Artifacts_${{ env.ARTIFACTS_SHA }} to some static name - 
#   mv Artifacts_${{ env.ARTIFACTS_SHA }} artifacts
    - name: What triggered this workflow?
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]
        then
           echo "Trigger: workflow_dispatch - with inputs.RUN_ID: ${{ inputs.RUN_ID }}"
        else
           echo "Trigger: workflow_run - with github.event.workflow_run.id data: ${{ github.event.workflow_run.id }}"
        fi

        
